{
    "0": "Firefly Sign \"Meteors on Earth\"",
    "1": "Firefly Sign \"Comets on Earth\"",
    "10": "Hidden Bug \"Hermit of an Endless Night\"",
    "11": "Hidden Bug \"Hermit of an Endless Night\"",
    "12": "Hidden Bug \"Hermit of an Endless Night\"",
    "20": "Deadly Toxin \"Venomous Moth's Dark Dance\"",
    "29": "Night Sparrow \"Midnight Chorus Master\"",
    "30": "Night Sparrow \"Midnight Chorus Master\"",
    "31": "Night Sparrow \"Midnight Chorus Master\"",
    "64": "Divine Art \"Omnidirectional Demon-Binding Ring\"",
    "65": "Divine Art \"Omnidirectional Dragon-Slaying Circle\"",
    "93": "Light Sign \"Earth Light Ray\"",
    "94": "Light Sign \"Earth Light Ray\"",
    "116": "Lunar Eyes \"Tele-Mesmerism (Remote Rabbit)\"",
    "117": "Lunar Eyes \"Tele-Mesmerism (Remote Rabbit)\"",
    "118": "Lunar Eyes \"Tele-Mesmerism (Remote Rabbit)\"",
    "125": "God Sign \"Genealogy of the Sky-Born\"",
    "126": "God Sign \"Genealogy of the Sky-Born\"",
    "127": "Revival \"Game of Life\"",
    "128": "Revival \"Game of Life\"",
    "129": "Resurrection \"Game of Rising\"",
    "130": "Resurrection \"Game of Rising\"",
    "135": "Curse of the Heavens \"Apollo 13\"",
    "136": "Curse of the Heavens \"Apollo 13\"",
    "137": "Curse of the Heavens \"Apollo 13\"",
    "138": "Curse of the Heavens \"Apollo 13\"",
    "139": "Esoterica \"Astronomical Entombing\"",
    "140": "Esoterica \"Astronomical Entombing\"",
    "141": "Esoterica \"Astronomical Entombing\"",
    "142": "Esoterica \"Astronomical Entombing\"",
    "143": "Forbidden Arcanum \"Hourai Elixir\"",
    "144": "Forbidden Arcanum \"Hourai Elixir\"",
    "145": "Forbidden Arcanum \"Hourai Elixir\"",
    "146": "Forbidden Arcanum \"Hourai Elixir\"",
    "151": "Impossible Request \"Dragon's Necklace -Five-Colored Shots-\"",
    "152": "Impossible Request \"Dragon's Necklace -Five-Colored Shots-\"",
    "153": "Divine Treasure \"Brilliant Dragon Barrette\"",
    "154": "Divine Treasure \"Brilliant Dragon Barrette\"",
    "159": "Impossible Request \"Fire Rat's Robe -Unhurried Mind-\"",
    "160": "Impossible Request \"Fire Rat's Robe -Unhurried Mind-\"",
    "194": "Limiting Edict \"Iwakasa's Moon Curse\"",
    "196": "Fujiwara \"Flaw of Forgiving Shrine\"",
    "198": "Forgiveness \"Honest Man's Death\"",
    "205": "\"Unseasonable Butterfly Storm\"",
    "210": "\"Tree-Ocean of Hourai\"",
    "214": "\"Fantasy Nature\"",
    "220": "\"Saigyouji Flawless Nirvana\""
}